#[colors]
#draw_bold_text_with_bright_colors = false
# [general]
import = ["rose-pine.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.glyph_offset]
x = 0
y = -1

[font.offset]
x = -1
y = -1

[font.bold]
family = "JetbrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetbrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetbrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_title = true
# dynamic_padding = true

[window.dimensions]
columns = 90
lines = 25

[window.padding]
x = 6
y = 6
