[dirs."/home/mrsandman/Music/2026/beholder/"]
selected_path = "/home/mrsandman/Music/2026/beholder/New Chains, Same Shackles - $uicideboy$.flac"
last_played_path = "/home/mrsandman/Music/2026/beholder/New Chains, Same Shackles - $uicideboy$.flac"
volume_percent = 40
shuffle = true
loop_mode = "LoopAll"
follow_playback = false
